[package]
name = "adblock-fetch"
version = "0.1.0"
edition = "2024"

[dependencies]
addr = "0.15.6"
clap = {version = "4.5.53", features = [ "derive" ] }
futures = "0.3.31"
reqwest = "0.12.28"
reqwest-middleware = "0.4.2"
reqwest-retry = "0.8.0"
tokio = { version = "1.48.0", features = ["full"] }
