[package]
name = "orgncf-generator"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { workspace = true }
thiserror = { workspace = true }
tree-sitter = { workspace = true }
tree-sitter-orgncf = { path = "../tree-sitter-orgncf" }

[dev-dependencies]
indoc = { workspace = true }
