[package]
name = "dns-block"
version = "0.5.1"
authors = ["Ovidiu Ionescu <ovidiu@ionescu.net>"]
edition = "2024"
description = "Simplify the list of ad and tracking servers to block"

[dependencies]
fnv = "*"
rayon = "*"
clap= { version = "*", features = ["derive"] }
log="*"
stderrlog="*"
indoc="1.0"
mimalloc = "*"
addr = "0"

[profile.release]
lto = true

